/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package snapshot

import (
	"encoding/json"
	"fmt"

	"github.com/spf13/cobra"

	"sigs.k8s.io/kind/pkg/cluster"
	"sigs.k8s.io/kind/pkg/cmd"
	snapshot "sigs.k8s.io/kind/pkg/internal/snapshot"
	"sigs.k8s.io/kind/pkg/log"

	"sigs.k8s.io/kind/pkg/internal/cli"
	"sigs.k8s.io/kind/pkg/internal/runtime"
)

// createFlagpole holds parsed flag values for `kinder snapshot create`.
type createFlagpole struct {
	// JSON enables JSON output for scripted consumers.
	JSON bool
	// SnapName is the explicit snapshot name (default: auto-generated "snap-YYYYMMDD-HHMMSS").
	SnapName string
}

// createFn is the test-injection point for the Create orchestration call.
// Production code calls snapshot.Create; tests substitute a fake.
var createFn = snapshot.Create

// newCreateCommand returns the `kinder snapshot create [cluster] [snap-name]` command.
func newCreateCommand(logger log.Logger, streams cmd.IOStreams) *cobra.Command {
	flags := &createFlagpole{}
	c := &cobra.Command{
		Use:   "create [cluster-name] [snap-name]",
		Short: "Create a snapshot of the named cluster (or auto-detected cluster)",
		Long: "Create a full cluster snapshot stored under ~/.kinder/snapshots/<cluster>/<snap-name>.tar.gz.\n\n" +
			"The snapshot bundles: etcd state, container images, local-path PV contents, and a\n" +
			"metadata manifest (k8s version, node image, topology, addon versions, sha256 digests).\n\n" +
			"WARNING: etcd contains Kubernetes Secrets in plain text; the snapshot archive is\n" +
			"stored with mode 0700 but treat it as sensitive data.\n\n" +
			"Arg disambiguation: with 2 args, args[0]=cluster, args[1]=snap-name.\n" +
			"With 1 arg, arg[0]=cluster (snap-name is auto-generated).\n" +
			"With 0 args, cluster is auto-detected when exactly one cluster exists.",
		Args: cobra.MaximumNArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			cli.OverrideDefaultName(cmd.Flags())
			return runCreate(logger, streams, flags, args)
		},
	}
	c.Flags().BoolVar(&flags.JSON, "json", false, "output JSON")
	c.Flags().StringVar(&flags.SnapName, "name", "", "explicit snapshot name (default: snap-YYYYMMDD-HHMMSS)")
	return c
}

func runCreate(logger log.Logger, streams cmd.IOStreams, flags *createFlagpole, args []string) error {
	var clusterName, snapName string
	switch len(args) {
	case 0:
		// Auto-detect cluster; snap-name auto-generated by Create.
	case 1:
		clusterName = args[0]
	case 2:
		clusterName = args[0]
		snapName = args[1]
	}
	// --name flag overrides positional snap-name.
	if flags.SnapName != "" {
		snapName = flags.SnapName
	}

	provider := cluster.NewProvider(
		cluster.ProviderWithLogger(logger),
		runtime.GetDefault(logger),
	)

	res, err := createFn(snapshot.CreateOptions{
		ClusterName: clusterName,
		SnapName:    snapName,
		Logger:      logger,
		Provider:    provider,
	})
	if err != nil {
		return err
	}

	if flags.JSON {
		return json.NewEncoder(streams.Out).Encode(res)
	}
	fmt.Fprintf(streams.Out, "Created snapshot %s (%s)\n", res.SnapName, humanizeBytes(res.Size))
	fmt.Fprintf(streams.Out, "  Path: %s\n", res.Path)
	fmt.Fprintf(streams.Out, "Tip: use `kinder snapshot prune --keep-last 3` to manage disk usage.\n")
	return nil
}
